### ISSUE TITLE
Total Endpoints Discovered graph misleading

### ISSUE THREAD

**Issue by rosskukulinski** [heptio/gimbal#101]
**Is this a BUG REPORT, PERFORMANCE REPORT or FEATURE REQUEST?**:

bug report

**What happened**:

Deployed `master` of Gimbal and looked at the Grafana dashboard for Gimbal Discovery.  The `Total Endpoints Discovered` graph is misleading because Endpoints are not the same as Endpoint Address available.

Scaling up a deployment in a upstream cluster from 1 Pod to 10 Pods results in the total endpoints graph remaining flat at 1.

**What you expected to happen**:

The graph should increase as remote deployments are scaled up or down.

As the term `Endpoints` is overloaded, we might consider renaming `Total Endpoints`  to `Remote Endpoint Addresses`.

**Anything else we should know**:

Right now we're graphing `kube_endpoint_labels ` but we should be using `kube_endpoint_address_available`.   The catch is that the kube-state-metrics code doesn't provide labels (which include the cluster name) in the `kube_endpoint_address_available` metric.

**Comment by stevesloka** [comment]
How helpful is graphing the total endpoints per cluster? We could show total per namespace, then allow users to drill down into a namespace and show total per service within.

**Comment by stevesloka** [comment]
@rosskukulinski this now resolved now that #108 is complete?

**Comment by rosskukulinski** [comment]
Yep! Thanks
