### ISSUE TITLE
Rename --cluster-name flags on discoverers

### ISSUE THREAD

**Issue by alexbrand** [heptio/gimbal#107]
The discovery naming conventions use "backend name" instead of "cluster name". We had a brief discussion on #102 about renaming the `--cluster-name` flag on the discoverers to `--backend-name`, so opening this issue to finish up that discussion.

**Comment by rosskukulinski** [comment]
Some other examples for a "service" that will accept traffic for a given "route":

HAPROXY: backend
NGINX: upstream
Google Cloud LB: backend
ELB: back-end
ZooKeeper: servers

----

I'm leaning towards `Backend` to represent a grouping of resources to be discovered.  Each Backend can expose one or more `Services`, which is a group of one or more `Endpoints`.

Backend: Kubernetes cluster, OpenStack Cluster, Ec2 region(?)
Service: Kubernetes Service, Openstack LbaaS, ec2 tags(?)
Endpoint: Kubernetes Pod, OpenStack VM, ec2 instance

**Comment by stevesloka** [comment]
Envoy has a terminology section which might be good for us to add: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/terminology
