### ISSUE TITLE
Discoverer watch for changes to secret

### ISSUE THREAD

**Issue by stevesloka** [heptio/gimbal#11]
The discoverer takes in a secret for access credentials to a remote cluster. It needs to watch for changes to this secret and update its configuration accordingly to allow for credential rotation. Could watch for file changes on disk or utilize a Controller to implement.

**Comment by rosskukulinski** [comment]
This was discussed on Monday and we agreed that we will leverage watching for file changes on disk rather than an external controller.

@stevesloka IIRC, we planned to have the discoverers exit and allow the pod to restart on secret change?

**Comment by stevesloka** [comment]
@rosskukulinski I think we can accomplish this with just docs. Do you think that's reasonable?

**Comment by rosskukulinski** [comment]
@stevesloka I'm ok with documentation for now, "update secret, delete pod".

**Comment by stevesloka** [comment]
I did a quick check and looks like we have it already documented:

- https://github.com/heptio/gimbal/blob/master/docs/kubernetes-discoverer.md#updating-credentials
- https://github.com/heptio/gimbal/blob/master/docs/openstack-discoverer.md#updating-credentials
