### ISSUE TITLE
Queue size metric does not seem to be accurate

### ISSUE THREAD

**Issue by alexbrand** [heptio/gimbal#117]
**Is this a BUG REPORT, PERFORMANCE REPORT or FEATURE REQUEST?**: BUG REPORT

**What happened**:
After creating hundreds of services in a backend cluster, the kubernetes discoverer increased the queue size metric as expected. However, after the discovery of all services was complete, the metric did not go to zero.

![image](https://user-images.githubusercontent.com/545723/40192548-afa8f942-59d2-11e8-8247-4fe2d0d63804.png)

**What you expected to happen**:
I would expect the metric to go to zero once all services have been processed. 

My gut feeling is that the problem is we are not updating the gauge when dequeuing items.

**How to reproduce it (as minimally and precisely as possible)**:
Create a bunch of services in the backend cluster and observe the metrics/charts.

**Comment by stevesloka** [comment]
I looked at the code and you are correct, there's no metric write after we've processed an item. Should be here: https://github.com/heptio/gimbal/blob/master/discovery/pkg/sync/queue.go#L128
