### ISSUE TITLE
Enable rolling update of Envoy daemonset

### ISSUE THREAD

**Issue by rosskukulinski** [heptio/gimbal#135]
**Is this a BUG REPORT, PERFORMANCE REPORT or FEATURE REQUEST?**:

Feature request

**What happened**:

I tied to update to a newer version of Envoy by running `kubectl apply -f deployment/contour/03-envoy.yaml` with a modified container image.  The `apply` took effect but the old envoy pods continued to run.

**What you expected to happen**:

I expected the Envoy daemonset to have implemented the rolling update strategy such that I don't have to manually delete Envoy pods after updating the daemonset configuration.

**Comment by stevesloka** [comment]
We should also take into account active connections and attempt to drain before rolling the pod: https://github.com/envoyproxy/envoy/issues/1990#issuecomment-341509716

**Comment by stevesloka** [comment]
I moved the active connections to a separate issue (#144)

**Comment by stevesloka** [comment]
Closed via #145
