### ISSUE TITLE
FEATURE REQUEST: Configurable request interval for the OpenStack performance

### ISSUE THREAD

**Issue by hmorikaw** [heptio/gimbal#156]
We should limit the OpenStack API request interval same as the kubernetes environment. 

We should configure request rate for the backend OpenStack API, and probably make it configurable by the user, as each environment will have different requirements and hardware capacity.

related issue #150

**Comment by rosskukulinski** [comment]
@alexbrand wouldn't this be covered by the `reconciliation-period` parameter: https://github.com/heptio/gimbal/blob/master/docs/openstack-discoverer.md?

**Comment by alexbrand** [comment]
@rosskukulinski Yes. The reconciliation period will cover the interval at which we call out to the OpenStack API. 

With that said, I don't fully understand this feature request. Is this about limiting the number of requests per second that are performed against the OpenStack API? Similar to how it is done in the Kubernetes client?

**Comment by rosskukulinski** [comment]
@hmorikaw could you provide some more details? Thanks!

**Comment by tomonarinakama** [comment]
@rosskukulinski This requests to make the interval to call OpenStack API be configurable by user. I guess it's already covered by reconciliation-period as you mentioned above, is that correct?

**Comment by rosskukulinski** [comment]
@tomonarinakama yes, that is correct.  the `reconciliation-period` (in seconds) parameter determines how often the OpenStack API will be queried.

Increasing the period will decrease the load on the OpenStack API but will increase the time it takes for changes in OpenStack to be updated in Gimbal.

Marking as closed.
