### ISSUE TITLE
Discoverer Metrics using Gauge instead of Histogram

### ISSUE THREAD

**Issue by rosskukulinski** [heptio/gimbal#163]
**Is this a BUG REPORT, PERFORMANCE REPORT or FEATURE REQUEST?**:

BUG REPORT

**What happened**:

The Prometheus metrics for CycleDurationMetric & APILatencyMetric are both currently of type Gauge when they should actually be type Histogram

**Comment by alexbrand** [comment]
@rosskukulinski Are there best practices around bucket sizing that you are familiar with? Or do you think we need to make them configurable?

**Comment by rosskukulinski** [comment]
I think we can probably take a decent crack at an initial bucket sizing.  If we later find out we need to make it configurable, we can do so.
