### ISSUE TITLE
Grafana Dashboard for IngressRoute Metrics

### ISSUE THREAD

**Issue by rosskukulinski** [heptio/gimbal#174]
Refs https://github.com/heptio/contour/issues/525

We should have a Grafana dashboard for visualizing information provided by the Contour metrics related to IngressRoutes.

**Comment by stevesloka** [comment]
@rosskukulinski I was thinking we need a new dashboard for this. Currently, we have `envoy` & `discoverer` metrics, this issue should add a `contour` dashboard?

**Comment by rosskukulinski** [comment]
Yes please. And maybe move he cds and lds graphs from ‘envoy’ to the new contour dash
