### ISSUE TITLE
Show P99 latency in envoy dashboards

### ISSUE THREAD

**Issue by alexbrand** [heptio/gimbal#190]
The current dashboards show P90 latency. We should either update that to display P99, or add an additional line that charts P99 latencies.

**Comment by rosskukulinski** [comment]
Fixed in #189

**Comment by alexbrand** [comment]
I am reopening this as I am only seeing P99 for upstream latencies, but not downstream latencies. Pinging @stevesloka to make sure I am not crazy, and confirm his change only modified the upstream latencies panel.

**Comment by stevesloka** [comment]
Bah yeah, I only did for upstream. I think maybe I misunderstood, can update to fix.

**Comment by alexbrand** [comment]
Sounds good @stevesloka. Assigning to you, but happy to take it if you're busy.

**Comment by stevesloka** [comment]
@alexbrand I added the P99 to the Downstream panel.
