### ISSUE TITLE
Gophercloud dep for openstack points to `master`

### ISSUE THREAD

**Issue by stevesloka** [heptio/gimbal#200]
The Openstack discoverer uses the Gophercloud repo as a dependency for authenticating to Openstack, however, it does not have releases and we point to `master` for the dep version (https://github.com/heptio/gimbal/blob/master/discovery/Gopkg.toml#L63).

This issue is to discuss if we should fork the repo and make a release so future builds do not break.

**Comment by alexbrand** [comment]
Would pointing to a specific commit in the dep manifest fix this issue? Keeping a fork sounds like a lot of work.

**Comment by stevesloka** [comment]
yeah that would work and it a better solution. We can combine that update with #201
