### ISSUE TITLE
OpenStack Discoverers: use loadbalancer's uuid instead of its name

### ISSUE THREAD

**Issue by hmorikaw** [heptio/gimbal#216]
**Describe the solution you'd like**
    I'd like gimbal discoverer to use loadbalancer's uuid instead of its name.

**What steps did you take and what happened:
    1. I create openstack loadbalancer which names 'foo:8080'.
    2. I configure the gimbal openstack discoverer. 
    3. The discoverer pod skips synchronization.
        ```
        time="2018-08-14T23:05:28Z" level=warning msg="skipping load balancer 'fb7b864b-bedd-4129-a90c-957b4fe2cf07' in project 'heptio' as it has an invalid name 'foo:8080'"
        ```
     This problem is caused by k8s name validation which skips some characters like '/', ':', '@' and so on.

**Environment:**

- Gimbal Cluster Kubernetes version (use `kubectl version`):  v1.9.5
- Backend Cluster versions (OpenStack and/or Kubernetes): OpenStack Pike (neutron version: 11.0.3.dev22)
- Gimbal version (Gimbal git repository tag): release-0.3.0-beta.2
- Contour version: v0.6.0-beta.2
- kubernetes-discoverer version: v0.3.0-beta.2
- openstack-discoverer version (if applicable): v0.3.0-beta.2

**Comment by rosskukulinski** [comment]
@hmorikaw we discussed this a long time ago and the feedback we received was that UUIDs were not user friendly, and that load balancer names were typically "valid" Kubernetes service names.  So we opted to improve the user-experience when LB names are _not_ valid.

We documented this behavior here: https://github.com/heptio/gimbal/blob/master/docs/discovery-naming-conventions.md#handling-names-that-contain-invalid-characters.

Do you feel that this was an invalid decision we all made?

**Comment by alexbrand** [comment]
We discussed the possibility of replacing unsupported characters with a hyphen (`-`).

One potential problem that was discussed was that of collisions. For example, an LB named "foo$bar" would translate to the same name as an LB named "foo@bar", namely `foo-bar`. However, we concluded that this is not a problem because we append the LB UUID during the translation process.

Another potential problem is that of LB names that start with an unsupported character. For example, an LB named "$foobar" would translate to "-foobar", which is an invalid Kubernetes service name. This, however, is not an issue because we prepend the backend name to the discovered services. 

The one thing that I am uneasy about is the ability to rename Load Balancers in OpenStack. In the case of a name change, the discoverer would delete the "old" service and create a "new" service. Are there any downsides here? Further, are there any edge cases that we are not thinking about?

**Comment by rosskukulinski** [comment]
After some further discussions, we're going to move to using load balancer UUID as the service name and then apply the LB name as a label to the Service.

This prevents the situation where an OpenStack load balancer name is changed (which is allowed) which then triggers a Service delete & create with new name (thus breaking all IngressRoutes pointing to that Service).

**Comment by rosskukulinski** [comment]
Service name: ${backendName}-${OS-UUID}

**Comment by hmorikaw** [comment]
> Service name: ${backendName}-${OS-UUID}

name validation still remains this problem.
```
time="2018-09-25T01:51:00Z" level=info msg="Started workers"
time="2018-09-25T01:51:44Z" level=warning msg="skipping load balancer '3bd1b586-5311-4b92-87ae-71b132cc3e3c' in project 'foo' as it has an invalid name 'bar:8080'"
```

**Comment by alexbrand** [comment]
Valid kubernetes label values are governed by the following rules:

> Valid label values must be 63 characters or less and must be empty or begin and end with an alphanumeric character ([a-z0-9A-Z]) with dashes (-), underscores (_), dots (.), and alphanumerics between.


Given that the openstack load balancer name is translated into a kubernetes label, the discoverer will massage the name into the label when necessary in the following way:
1. Replace any disallowed character with a dash (`-`). 
2. Prepend `lb` to the name when it does not begin with an alphanumeric character
3. Append `lb` to the name when it does not begin with an alphanumeric character

Examples:

| Load Balancer name | Label value |
|----------------------|-----------|
| bar:8080| bar-8080|
|foo!@#$%^&*()_+bar | foo----------_-bar |
| foo-bar_BAZ.123 | foo-bar_BAZ.123 (no change) |
| foo! | foo-lb |
| !foo | lb-foo|
|!foo! | lb-foo-lb |
| foo- | foo-lb|
| foo_ | foo_lb|
|foo.| foo.lb|

**Comment by rosskukulinski** [comment]
@alexbrand does it prepend/append with `lb` or `-lb`/`lb-`?

**Comment by alexbrand** [comment]
The reasoning for append/prepend `lb` without dashes is that we only append/prepend when there's a special char at the beginning/end. Thus, the char before/after `lb` will always be either `-`,`_`, or `.`.

For example, `foo!` becomes `foo-lb` instead of `foo--lb`.

Thoughts?

**Comment by rosskukulinski** [comment]
ahh, I understand.  👍
