### ISSUE TITLE
Limit OpenStack discovery with white list

### ISSUE THREAD

**Issue by hmorikaw** [heptio/gimbal#241]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

The OpenStack discoverer sync cycle spend too long when OpenStack cluster has too many projects.
So, I'd like to limit sync projects by white list.

In my cluster, which has about 3900 projects,  one sync cycle spends about 30 min.
So, OpenStack LBaaS operations don't sync instantly. 
```
$ kubectl logs openstack-discoverer-5556b6dcbc-ptj6n -n gimbal-discovery | grep 'dreco-001/openstack-626c5bf1-3cf8-438a-b6a1-e20419126eee'

time="2018-10-28T22:20:33Z" level=info msg="Successfully handled: update service 'dreco-001/openstack-626c5bf1-3cf8-438a-b6a1-e20419126eee'"
time="2018-10-28T22:51:58Z" level=info msg="Successfully handled: update endpoints 'dreco-001/openstack-626c5bf1-3cf8-438a-b6a1-e20419126eee'"
time="2018-10-28T22:51:59Z" level=info msg="Successfully handled: update service 'dreco-001/openstack-626c5bf1-3cf8-438a-b6a1-e20419126eee'"
time="2018-10-28T23:23:19Z" level=info msg="Successfully handled: update endpoints 'dreco-001/openstack-626c5bf1-3cf8-438a-b6a1-e20419126eee'"
time="2018-10-28T23:54:43Z" level=info msg="Successfully handled: update service 'dreco-001/openstack-626c5bf1-3cf8-438a-b6a1-e20419126eee'"
time="2018-10-28T23:54:43Z" level=info msg="Successfully handled: update endpoints 'dreco-001/openstack-626c5bf1-3cf8-438a-b6a1-e20419126eee'"
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Gimbal Cluster Kubernetes version (use `kubectl version`):  v1.12.1
- Backend Cluster versions (OpenStack and/or Kubernetes): stable/pike
- Gimbal version (Gimbal git repository tag): v0.3.1
- Contour version: v0.6.0
- openstack-discoverer version (if applicable): v0.3.1
- Cloud provider or hardware configuration: Xeon E5-2650Lv3 1.80GHz / 512GBMEM / SAS 300GB x2 / RAID1*1vol / NVMeSSD 3.2TB /Intel X540 10Gbase-T 2port
- OS (e.g. from /etc/os-release): CentOS Linux 7.5
- Kernel (e.g. `uname -a`): 3.10.0-862.14.4.el7.x86_64

**Comment by rosskukulinski** [comment]
This was resolved in #249, Thanks @hmorikaw for your PR!
