### ISSUE TITLE
Use kube-state-metrics for counting the number of services and endpoints discovered

### ISSUE THREAD

**Issue by alexbrand** [heptio/gimbal#53]
The current grafana dashboard displays the total number of services and endpoints that have been discovered. The dashboard computes these numbers based on the `event_timestamp` metric, which indicates the last time a service or endpoint was updated.

The problem with using this metric for computing the count is that if the discoverer is restarted, the grafana dashboard will display zero until the services/endpoints are updated (because the "event_timestamp" metric will not be set).

**Comment by stevesloka** [comment]
I think if we want to graph how many services exist, we should use the metric from the `kube-state-metrics` that expose those. We can use the Gimbal services/endpoints metrics to help find rates of discovery.

**Comment by alexbrand** [comment]
Ah good point! And use the gimbal label to filter the services/endpoints to the ones that have been discovered.

**Comment by stevesloka** [comment]
@alexbrand do you think this can be closed or should it be renamed to update dashboard to use kube-state-metrics?

**Comment by alexbrand** [comment]
I think updating the issue would be best, so that we track it. Will update.
