### ISSUE TITLE
Discoverer: Initialize gauge metrics to zero

### ISSUE THREAD

**Issue by alexbrand** [heptio/gimbal#56]
Some of the metrics exposed by the discoverer components should probably be initialized to zero so that they show up in grafana. An example that comes to mind is the number of discovery errors.

**Comment by alexbrand** [comment]
Hmmm good point. Hadn't thought about that. In that case, I am not sure we can initialize metrics to zero then.

**Comment by stevesloka** [comment]
Going to close this for now, can re-open if we determine we need to address this in the future.
