### ISSUE TITLE
Enable route configuration across multiple services

### ISSUE THREAD

**Issue by rosskukulinski** [heptio/gimbal#73]
The Kubernetes Ingress object limits a single 'service' per Route path.  For Gimbal, users should be able to define multiple Services (from Kubernetes or OpenStack clusters) that will receive traffic for a given route.  Users should be able to define the load balancing strategy (RoundRobin, Random, Least load, EWMA).

This enables a wide variety of use-cases including weight-shifting, A/B testing, etc.

**Comment by ncdc** [comment]
@rosskukulinski fwiw, I got around this in my kubecon demo by creating multiple entries in the ingress's rules for the same path (e.g. `/`), with each entry pointing to a different service. I also hacked contour to support this model. Not saying we should necessarily do that, but it's an option if we do want to continue using ingress & support multiple services per route path.

**Comment by rosskukulinski** [comment]
Fixed in v0.2 with #118
