### ISSUE TITLE
Active Health Checking of Endpoints

### ISSUE THREAD

**Issue by rosskukulinski** [heptio/gimbal#74]
While Kubernetes Services support native health-checking, other upstream systems, including OpenStack, do not include health checking.

Gimbal should allow active health checking of upstream endpoints (grouped by Service).

Active health checking of Endpoints

**Comment by rosskukulinski** [comment]
https://www.envoyproxy.io/docs/envoy/latest/configuration/cluster_manager/cluster_stats#health-check-statistics

**Comment by rosskukulinski** [comment]
Fixed with #118 in v0.2

**Comment by stevesloka** [comment]
// ref: https://github.com/heptio/contour/issues/283

**Comment by stevesloka** [comment]
// ref: heptio/contour#442

**Comment by rosskukulinski** [comment]
This landed in https://github.com/heptio/contour/pull/498
