### ISSUE TITLE
Secure envoy admin interface for metrics

### ISSUE THREAD

**Issue by stevesloka** [heptio/gimbal#80]
To gather Prometheus metrics from Envoy the admin interface is exposed (https://github.com/heptio/gimbal/blob/master/deployment/contour/02-deployment.yaml#L49). We should find a way to not expose the Envoy admin functionality but still expose the Prometheus metrics endpoint.

**Comment by stevesloka** [comment]
Issue in Contour: https://github.com/heptio/contour/issues/376
PR to Contour: https://github.com/heptio/contour/pull/377

**Comment by rosskukulinski** [comment]
Fixed in #105
