### ISSUE TITLE
Allow Prometheus data to persist to PVC

### ISSUE THREAD

**Issue by stevesloka** [heptio/gimbal#99]
Currently, Prometheus data is stored in the pod's temporary storage. We need to make an example which mounts the data on a node's local storage. Should make it apply the deployment to the same node and utilized PV / PVC's accordingly.

**Comment by rosskukulinski** [comment]
After talking with @stevesloka this afternoon, this can probably be handled as a documentation improvement rather than explicit PV/PVC details.  Most users will likely either have their own existing prometheus deployments or will be leveraging other tools.
